services:
  backup:
    container_name: duplicacy
    build:
      context: .
      args:
        DUPLICACY_VERSION: 3.2.4
    restart: always
    environment:
      BACKUP_SCHEDULE: "0 */6 * * *"
      PRUNE_SCHEDULE: "0 2 * * *"
      COPY_SCHEDULE: ""
      DUPLICACY_BACKUP_OPTIONS: "-stats"
      DUPLICACY_PRUNE_OPTIONS: "-keep 60:360 -keep 30:180 -keep 7:30 -keep 2:14 -keep 1:7"
      DUPLICACY_COPY_OPTIONS: ""
    volumes:
      - duplicacy_store:/data
      - ./gcd-token.json:/app/gcd-token.json:ro
      - ./.duplicacy:/data/.duplicacy

volumes:
  duplicacy_store:
